{
 "title": "UrbanOS Phoenix API Metrics",
 "description": "Metrics of all Phoenix APIs in the cluster that implement Prometheus",
 "tags": [
  "Elixir",
  "Phoenix",
  "API"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "app", "query": "label_values(app)" }
  ]
 },
 "panels": [
  {
   "title": "Avg Action Call Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(phoenix_controller_call_duration_microseconds_sum{app=~\"$app\",controller!~\".*Health.*\"}[2m])) without (instance)/sum(rate(phoenix_controller_call_duration_microseconds_count{app=~\"$app\",controller!~\".*Health.*\"}[2m])) without (instance)",
     "legendFormat": "{{app}}/{{action}}"
    }
   ]
  },
  {
   "title": "Phoenix API Call Rate By Action",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Rate of Requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(phoenix_controller_call_duration_microseconds_count{app=~\"$app\",controller!~\".*Health.*\"}[2m])) without (instance)",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Call Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(phoenix_controller_call_duration_microseconds_bucket{app=~\"$app\",controller!~\".*Health.*\"}[2m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Phoenix API Call Rate By App",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Rate of Requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(phoenix_controller_call_duration_microseconds_count{app=~\"$app\",controller!~\".*Health.*\"}[2m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}